from parsing_tests import *
from test_backup_tools import *
from test_briefcase_api import *
from test_command_syncd_deleted_instances_fix import *
from test_digest_authentication import *
from test_encrypted_submissions import *
from test_form_submission import *
from test_import_tools import *
from test_models import *
from test_publish_xls import * 
from test_simple_submission import *
from test_submissionTime_validation import *
from test_update_xform_uuid import * 
from test_webforms import *