from test_audit_log import *
from test_base import *
from test_crowdforms import *
from test_csv_export import *
from test_form_api import *
from test_form_api_delete import *
from test_form_auth import *
from test_form_edit import *
from test_form_enter_data import *
from test_form_errors import *
from test_form_exports import *
from test_form_gallery import *
from test_form_metadata import *
from test_form_permissions import *
from test_form_public_api import *
from test_form_show import *
from test_form_show_submission import *
from test_google_doc import *
from test_google_docs_export import *
from test_gps import *
from test_http_auth import *
from test_kml_export import *
from test_past_bugs import *
from test_people_roles import *
from test_process import *
from test_user_id_string_unique_together import *
from test_user_login import *
from test_user_profile import *
from test_user_settings import *